# Generated by Django 4.1.7 on 2023-06-24 04:05

import account.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=35, unique=True, verbose_name='نام کاربری')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='زمان ثبت نام')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='زمان خروج')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر اصلی')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_staff', models.BooleanField(default=False, verbose_name='  کارمند')),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile, null=True, upload_to=account.models.get_imag_profile)),
                ('hide_email', models.BooleanField(default=False, verbose_name='ایمیل نمایش داده شود ؟ ')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
